#!/bin/bash

rundir="$(dirname $(readlink -f $0))"
cd "$rundir" || exit 1

modification_time(){
  python3 -c "import os; print(int(os.path.getmtime('$1')))"
}

export VIRTUAL_ENV="${VIRTUAL_ENV:-${rundir}/venv}"

create_env(){
   set -e
   rm -rf "${VIRTUAL_ENV}"
   python3 -m venv "${VIRTUAL_ENV}"
   source "${VIRTUAL_ENV}/bin/activate"
   pip install -r "${rundir}/requirements.txt"
   touch -r "${rundir}/requirements.txt" "${VIRTUAL_ENV}/bin/activate"
   set +e
}


if ! [ -d "${VIRTUAL_ENV}" ] ;then
   echo "Creating venv: ${VIRTUAL_ENV}" >&2
   echo
   create_env
elif [[ "$(modification_time "${rundir}/requirements.txt")" -gt "$(modification_time "${VIRTUAL_ENV}/bin/activate")" ]];then
   echo "Recreating venv: ${VIRTUAL_ENV}" >&2
   echo
   create_env
else
   source "${VIRTUAL_ENV}/bin/activate"
fi


if [ "$1" = "deps" ];then
   exit 0
fi

export PYTHONPATH="$rundir/src/"
exec "${VIRTUAL_ENV}/bin/python" -m openstack_workload_generator "$@"
