#!/bin/bash

rundir="$(dirname $(readlink -f $0))/"
cd "$rundir" || exit 1

modification_time(){
  python3 -c "import os; print(int(os.path.getmtime('$1')))"
}

create_env(){
   set -e
   rm -rf "${rundir}/venv"
   python3 -m venv "${rundir}/venv"
   source "${rundir}/venv/bin/activate"
   pip install -r "${rundir}/requirements.txt"
   touch -r "${rundir}/requirements.txt" "${rundir}/venv/bin/activate"
   set +e
}


if ! [ -d "${rundir}/venv" ] ;then
   echo "Creating venv: ${rundir}/venv"
   echo
   create_env
elif ( [[ "$(modification_time "${rundir}/requirements.txt")" -gt "$(modification_time "${rundir}/venv/bin/activate")" ]] ||
       [[ "$(modification_time "${rundir}/venv/sum/sum")" -gt  "$(modification_time "${rundir}/venv/bin/activate")" ]]
     );
then
   echo "Recreating venv: ${rundir}/venv"
   echo
   create_env
else
   source "${rundir}/venv/bin/activate"
fi


if [ "$1" = "deps" ];then
   exit 0
fi
cd "$rundir" || exit 1
source venv/bin/activate
exec python3 $rundir/src/openstack-workload-generator/__main__.py "$@"
